import {
  Home as HomeIcon,
  Dashboard as DashboardIcon,
  Settings as SettingsIcon,
  People as PeopleIcon,
  Notifications as NotificationsIcon,
  AccountCircle as AccountCircleIcon,
  Mail as MailIcon,
  CalendarToday as CalendarTodayIcon,
  ShoppingCart as ShoppingCartIcon,
  ShoppingBag as ShoppingBagIcon,
  Search as SearchIcon,
  Edit as EditIcon,
  Delete as DeleteIcon,
  Save as SaveIcon,
  Add as AddIcon,
  Remove as RemoveIcon,
  Info as InfoIcon,
  Warning as WarningIcon,
  Error as ErrorIcon,
  Check as CheckIcon,
  Close as CloseIcon,
  Folder as FolderIcon,
  FileCopy as FileCopyIcon,
  Bookmark as BookmarkIcon,
  Description as DescriptionIcon,
  Business as BusinessIcon,
  List as ListIcon,

  // 추가 아이콘들
  Menu as MenuIcon,
  ExpandMore as ExpandMoreIcon,
  ChevronRight as ChevronRightIcon,
  Person as PersonIcon,
  Group as GroupIcon,
  Work as WorkIcon,
  School as SchoolIcon,
  Article as ArticleIcon,
  Assignment as AssignmentIcon,
  UploadFile as UploadFileIcon,
  Download as DownloadIcon,
  Attachment as AttachmentIcon,
  BusinessCenter as BusinessCenterIcon,
  WorkHistory as WorkHistoryIcon,
  Security as SecurityIcon,
  Build as BuildIcon,
  MenuBook as MenuBookIcon,
  Category as CategoryIcon,
  Campaign as CampaignIcon,
  HelpOutline as HelpOutlineIcon,
} from '@mui/icons-material';

export const ICON_MAP: Record<string, React.ElementType> = {
  // 기존
  Home: HomeIcon,
  Dashboard: DashboardIcon,
  Settings: SettingsIcon,
  People: PeopleIcon,
  Notifications: NotificationsIcon,
  AccountCircle: AccountCircleIcon,
  Mail: MailIcon,
  CalendarToday: CalendarTodayIcon,
  ShoppingCart: ShoppingCartIcon,
  ShoppingBag: ShoppingBagIcon,
  Search: SearchIcon,
  Edit: EditIcon,
  Delete: DeleteIcon,
  Save: SaveIcon,
  Add: AddIcon,
  Remove: RemoveIcon,
  Info: InfoIcon,
  Warning: WarningIcon,
  Error: ErrorIcon,
  Check: CheckIcon,
  Close: CloseIcon,
  Folder: FolderIcon,
  FileCopy: FileCopyIcon,
  Bookmark: BookmarkIcon,
  Description: DescriptionIcon,
  Business: BusinessIcon,
  List: ListIcon,

  // 추가
  Menu: MenuIcon,
  ExpandMore: ExpandMoreIcon,
  ChevronRight: ChevronRightIcon,
  Person: PersonIcon,
  Group: GroupIcon,
  Work: WorkIcon,
  School: SchoolIcon,
  Article: ArticleIcon,
  Assignment: AssignmentIcon,
  UploadFile: UploadFileIcon,
  Download: DownloadIcon,
  Attachment: AttachmentIcon,
  BusinessCenter: BusinessCenterIcon,
  WorkHistory: WorkHistoryIcon,
  Security: SecurityIcon,
  Build: BuildIcon,
  MenuBook: MenuBookIcon,
  Category: CategoryIcon,
  Campaign: CampaignIcon,
  HelpOutline: HelpOutlineIcon,
};

export function getMenuIcon(iconName?: string): React.ElementType | undefined {
  if (!iconName) return undefined;
  return ICON_MAP[iconName];
}

export const ICON_NAMES = Object.keys(ICON_MAP);
